# Generated by Django 5.1.6 on 2025-02-25 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_blog_blogcomment_blograting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="allow_comments",
        ),
    ]
