# Generated by Django 5.1.6 on 2025-02-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_remove_blog_allow_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="blogThumbnails/"),
        ),
    ]
