# Generated by Django 5.1.6 on 2025-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="esewa_transaction_uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
